version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn lint
            - run: yarn test
            - run: yarn build
  deployment:
    steps:
      - checkout
      - run:
          name: Deploy to Surge
          command: surge --project ./build --domain dmaslov.surge.sh
workflows:
  build:
    jobs:
      - build-and-test
  deployment:
    jobs:
      - deployment:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
